// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// UploadFile provides a mock function with given fields: ctx, key, file, contentType
func (_m *Client) UploadFile(ctx context.Context, key string, file []byte, contentType string) (string, error) {
	ret := _m.Called(ctx, key, file, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) (string, error)); ok {
		return rf(ctx, key, file, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) string); ok {
		r0 = rf(ctx, key, file, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, string) error); ok {
		r1 = rf(ctx, key, file, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type Client_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - file []byte
//   - contentType string
func (_e *Client_Expecter) UploadFile(ctx interface{}, key interface{}, file interface{}, contentType interface{}) *Client_UploadFile_Call {
	return &Client_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, key, file, contentType)}
}

func (_c *Client_UploadFile_Call) Run(run func(ctx context.Context, key string, file []byte, contentType string)) *Client_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *Client_UploadFile_Call) Return(_a0 string, _a1 error) *Client_UploadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_UploadFile_Call) RunAndReturn(run func(context.Context, string, []byte, string) (string, error)) *Client_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
